var countries = {
    "BN": "ORCHIDS The International School - CBSE School in Bannerghatta, Sy. No.93/2 situated at Hommadevanahalli Village,    Begur Hobli, Bengaluru South Taluk,    Bangalore,Karnataka-560 083 ", 
    "BTMP": "ORCHIDS The International School - 2nd Main Rd, Duo Enclave, BTM Layout III Stage, Bilekahalli, Bangalore, Karnataka 560076", 
    "BTMP2":"ORCHIDS The International School - 3rd main, 6th Cross Rd, near Vijayas Archery Academy, Munivenkatppa Layout, Bilekahalli, Bangalore, Karnataka 560076, India",
    "JL": "ORCHIDS The International School - Behind PF quarters, Near HMT Theatre,Sector-2, HMT Colony,Jalahalli Village, Jalahalli,Bengaluru, Karnataka,Bangalore-560013",
    "CVR":"ORCHIDS The International School - Khata no:152, CV Raman Nagar, Survey no 136/3B, 7th Cross Road Vibhutipura Village, Jagadish Nagar, New Tippasandra, Bangalore, Karnataka 560075, India",
    "HAR":"ORCHIDS The International School - Survey No 15, Haralur village, Varthur Hobli, Taluk, Bangalore, Karnataka 560103",
    "HOR":"ORCHIDS The International School - Sy. No 63 Horamavu Agara Road, Hobli, K.R. Puram, Bengaluru, Karnataka 560043",
    "BOR":"ORCHIDS The International School - PLOT # 3/3A, R.S.C. OPP SHREE DARSHAN SOCIETY, SHIMPOLI ROAD,GORAI - 1,, NEAR GANESH DURGA TEMPLE & BEST OFFICER QUARTERS, BORIVALI WEST, MUMBAI, Mumbai, Maharashtra 400092, India",
    "DOM":"ORCHIDS The International School - DNC MULTIPURPOSE HIGH SCHOOL CAMPUS, DNC Rd, Sudam Wadi, Dombivli East, Dombivli, Maharashtra 421201",
    "KOP":"ORCHIDS The International School - Gahlot Hall, 59, Gyan Vikas Road, near D-Mart, Sector 14, Kopar Khairane, Navi Mumbai, Maharashtra 400709",
    "KOP2":"ORCHIDS The International School - Plot No. 23, Sector 1, Kopar Khairane, Navi Mumbai, Maharashtra 400709, India",
    "BACH":"ORCHIDS The International School in Bachupally D no. 6-149/5/B,Survey No : 422&422/1 near Dollar Meadows, Bowrampet Hyderabad, Telangana 500043 India",
    "NBC":"ORCHIDS The International School - New Braham Colony, 131001, Delhi Road, Sonepat, nearby ICICI Bank, Sonipat, Haryana 131001",
    "GHRD":"ORCHIDS The International School - Chamaria Road, NH-71A, Gohana Rd, Rohtak, Haryana 124001",
    "KORD": "ORCHIDS The International School - Bokhara Road Railway Crossing, Koradi Rd, Nagpur, Maharashtra 440023",
    "JKA":"ORCHIDS The International School - Thakurpukur - Bibirhat - Bakhrahat - Raipur Rd, Rasapunja, Kolkata, Raypur, West Bengal 700104",
    "MHG":"ORCHIDS The International School - Badu Rd, Shri Nagar, Netaji Nagar, Madhyamgram, Kolkata, West Bengal 700129",
    "NTW":"ORCHIDS The International School - Education & Research Foundation, ACHARYA MAHAPRAGYA MAHASHRAMAN, Major Arterial Road, Jodthbhim, South-East, Newtown, Kolkata, New Town, West Bengal 700156, India",
    "NEV":"ORCHIDS The International School - Nevta Road, Narayan-Y-Block, Khatwara, Jaisinghpura, Mahapura, Bhankrota,  302026",
    "BHRD":"ORCHIDS The International School - Near Medical College Bypass Junction Bhedaghat, Road, Garha, Jabalpur, Madhya Pradesh 482003",
    "ARSQ":"ORCHIDS The International School - Ujjain - Indore Rd, near MR 10 Road, Bhawrasla, Indore, Madhya Pradesh 453555",
    "MNG":"ORCHIDS The International School - AB Rd, Near Mangalia toll naka, Indore, Madhya Pradesh 453771",
    "DWEX":"ORCHIDS The International School - Tata Housing, Sector 113, Bajghera, Gurugram, Haryana 122017",
    "SOY":"ORCHIDS The International School - Block G, South City I, Sector 41, Gurugram, Haryana 122003",
    "DW19":"ORCHIDS The International School - Dwarka Goyla Dairy Rd, near Sector 19, Dwarka, New Delhi, Delhi, 110071",
    "HNRD":"ORCHIDS The International School - National Highway 12, Narmadapuram Rd, Ratanpur Sadak, Bhopal, Madhya Pradesh 462026",
    "TCH":"ORCHIDS The International School - Gut No 35, Adgaon Bk, Maharashtra 431007",
    "PLKI":"ORCHIDS The International School - Bharathiyar St, BHEL Nagar, Pallikaranai, Chennai, Tamil Nadu 600100",
    "THPK":"ORCHIDS The International School - 274/8, 4th Street Okkiyam, Thuraipakkam, near COGNIZANT TCO, Chennai, Tamil Nadu 600097",
    "JBHL":"C9RX+Q9F, Road Number 36, 1, opposite lane of Balaji Grand Bazaar, Kakatiya Hills, Guttala_Begumpet, Kavuri Hills, Jubilee Hills, Hyderabad, Telangana 500033, India",
    "BCPY":"ORCHIDS The International School - D no. 6-149/5/B,Survey No : 422&422/1, near Dollar Meadows, Bowrampet, Hyderabad, Telangana 500043",
    "HNWD":"ORCHIDS The International School - Ghotawade, Mulkhed, Road, Pune, Maharashtra 412115",
    "CIWD":"ORCHIDS The International School - Next to Luxury Living, Near Yashopuram Housing Society, Gawade Nagar Chinchwad Pimpri, Chinchwad, Pune, Maharashtra 411033",
    "RAJ":"ORCHIDS The International School in Rajajinagar, 7, 3rd cross, 14th main, Prakash Nagar, Srirampura, Bengaluru, Karnataka 560021",
    "MAHA":"ORCHIDS The International School in Mahalakshmi Layout,9/6, 4th Cross Rd, Mahalakshmipuram Layout, Mahalakshmi Layout, Bengaluru, Karnataka 560086, India",

}
